import AppKit
import os.log

// MARK: - Icon Color Field (toolbar icons only)

/// Which theme color an icon uses — only for toolbar icons that are recolored.
enum IconColorField {
    case orange, blue, yellow, green, cyan, magenta, red, comment, fg

    func resolve(_ theme: Theme) -> String {
        switch self {
        case .orange:  return theme.orange
        case .blue:    return theme.blue
        case .yellow:  return theme.yellow
        case .green:   return theme.green
        case .cyan:    return theme.cyan
        case .magenta: return theme.magenta
        case .red:     return theme.red
        case .comment: return theme.fgComment
        case .fg:      return theme.fg
        }
    }
}

// MARK: - Toolbar Icon Definition

private struct ToolbarIconDef {
    let name: String
    let color: IconColorField
}

/// Toolbar icons that use monochrome SVGs recolored with theme colors.
private let toolbarIcons: [ToolbarIconDef] = [
    ToolbarIconDef(name: "toolbar-sidebar", color: .fg),
    ToolbarIconDef(name: "toolbar-plus", color: .fg),
    ToolbarIconDef(name: "toolbar-eye-open", color: .fg),
    ToolbarIconDef(name: "toolbar-eye-closed", color: .fg),
    ToolbarIconDef(name: "toolbar-collapse", color: .fg),
    ToolbarIconDef(name: "toolbar-refresh", color: .fg),
    ToolbarIconDef(name: "toolbar-new-file", color: .fg),
    ToolbarIconDef(name: "toolbar-new-folder", color: .fg),
    ToolbarIconDef(name: "pin", color: .comment),
]

// MARK: - Material Icon Mapping (JSON-driven)

/// Parsed from icon-mapping.json generated by scripts/generate-icon-mapping.py.
private struct MaterialIconMapping: Decodable {
    let fileIcons: [String: String]               // icon name -> SVG filename
    let fileSuffixes: [String: String]             // extension -> icon name
    let fileStems: [String: String]                // lowercase filename -> icon name
    let directoryIcons: DirectoryIcons             // default folder icons
    let namedDirectories: [String: [String]]       // dir name -> [collapsed.svg, expanded.svg]

    struct DirectoryIcons: Decodable {
        let collapsed: String
        let expanded: String
    }

    enum CodingKeys: String, CodingKey {
        case fileIcons = "file_icons"
        case fileSuffixes = "file_suffixes"
        case fileStems = "file_stems"
        case directoryIcons = "directory_icons"
        case namedDirectories = "named_directories"
    }
}

// MARK: - SVG Recoloring (toolbar icons only)

/// Pre-compiled regex for recoloring SVG fill/stroke attributes.
private let fillRegex: NSRegularExpression? = {
    guard let regex = try? NSRegularExpression(pattern: ##"(fill|stroke)="#[0-9A-Fa-f]{3,8}""##) else {
        os_log(.error, "Failed to compile SVG color regex")
        return nil
    }
    return regex
}()

/// Replaces hex fill/stroke attribute values in an SVG string with a theme color.
private func recolorSVG(_ svg: String, color: String) -> String {
    guard let regex = fillRegex else { return svg }
    let colorValue = color.hasPrefix("#") ? color : "#\(color)"
    return regex.stringByReplacingMatches(
        in: svg,
        range: NSRange(svg.startIndex..., in: svg),
        withTemplate: "$1=\"\(colorValue)\""
    )
}

// MARK: - Icon Cache

/// Loads material file/folder icons (pre-colored) and toolbar icons (theme-recolored).
/// Material icons are loaded lazily on first access. Toolbar icons rebuild on theme change.
final class IconCache {

    // Toolbar icons: monochrome SVGs recolored with theme colors.
    private var toolbarImages: [String: NSImage] = [:]
    private var toolbarSVGs: [String: String] = [:]

    // Material icons: pre-colored SVGs loaded lazily.
    private var materialImages: [String: NSImage] = [:]
    private var materialDir: URL?

    // Mapping data parsed from JSON.
    private var mapping: MaterialIconMapping?

    init(theme: Theme) {
        loadMapping()
        loadToolbarSVGs()
        buildToolbarIcons(theme: theme)
    }

    // MARK: - Setup

    private func loadMapping() {
        guard let iconsURL = Bundle.appResources.url(forResource: "icons", withExtension: nil) else {
            NSLog("IconCache: icons resource directory not found in bundle")
            return
        }
        let matDir = iconsURL.appendingPathComponent("material")
        materialDir = matDir

        let jsonURL = matDir.appendingPathComponent("icon-mapping.json")
        guard let data = try? Data(contentsOf: jsonURL) else {
            NSLog("IconCache: icon-mapping.json not found at \(jsonURL.path)")
            return
        }
        do {
            mapping = try JSONDecoder().decode(MaterialIconMapping.self, from: data)
        } catch {
            NSLog("IconCache: Failed to parse icon-mapping.json: \(error)")
        }
    }

    private func loadToolbarSVGs() {
        guard let iconsURL = Bundle.appResources.url(forResource: "icons", withExtension: nil) else { return }
        for def in toolbarIcons {
            let svgURL = iconsURL.appendingPathComponent("\(def.name).svg")
            if let svgString = try? String(contentsOf: svgURL, encoding: .utf8) {
                toolbarSVGs[def.name] = svgString
            }
        }
    }

    private func buildToolbarIcons(theme: Theme) {
        toolbarImages.removeAll()
        for def in toolbarIcons {
            guard let svg = toolbarSVGs[def.name] else { continue }
            let color = def.color.resolve(theme)
            let recolored = recolorSVG(svg, color: color)
            if let image = renderSVG(recolored, size: 16) {
                toolbarImages[def.name] = image
            }
        }
    }

    /// Rebuilds toolbar icons for a new theme. Material icons are unaffected.
    func rebuild(theme: Theme) {
        buildToolbarIcons(theme: theme)
    }

    // MARK: - Material Icon Loading (lazy)

    /// Loads a material SVG by filename, caching the result.
    private func materialImage(svgFilename: String) -> NSImage? {
        if let cached = materialImages[svgFilename] {
            return cached
        }
        guard let dir = materialDir else { return nil }
        let url = dir.appendingPathComponent(svgFilename)
        guard let data = try? Data(contentsOf: url),
              let image = NSImage(data: data) else { return nil }
        image.size = NSSize(width: 16, height: 16)
        materialImages[svgFilename] = image
        return image
    }

    /// Resolves an icon name to an NSImage via the file_icons mapping.
    private func materialIcon(name: String) -> NSImage? {
        guard let svgFilename = mapping?.fileIcons[name] else { return nil }
        return materialImage(svgFilename: svgFilename)
    }

    // MARK: - Rendering

    private func renderSVG(_ svg: String, size: CGFloat) -> NSImage? {
        guard let data = svg.data(using: .utf8) else { return nil }
        guard let image = NSImage(data: data) else { return nil }
        image.size = NSSize(width: size, height: size)
        return image
    }

    // MARK: - Public API

    /// Returns the icon for a file or directory.
    func icon(filename: String, isDirectory: Bool, expanded: Bool) -> NSImage? {
        guard let mapping else { return nil }

        if isDirectory {
            return directoryIcon(name: filename, expanded: expanded, mapping: mapping)
        }
        return fileIcon(filename: filename, mapping: mapping)
    }

    /// Returns a toolbar icon by name. Falls back to material icons for
    /// non-toolbar names like "console" and "image" (used by TabManager).
    func toolbarIcon(name: String) -> NSImage? {
        return toolbarImages[name] ?? materialIcon(name: name)
    }

    // MARK: - File Icon Resolution

    private func fileIcon(filename: String, mapping: MaterialIconMapping) -> NSImage? {
        let lower = filename.lowercased()

        // 1. Exact filename match (e.g. "Dockerfile", ".gitignore")
        if let iconName = mapping.fileStems[lower] {
            if let img = materialIcon(name: iconName) { return img }
        }

        // 2. Extension match
        if let dotIndex = lower.lastIndex(of: ".") {
            let ext = String(lower[lower.index(after: dotIndex)...])
            if let iconName = mapping.fileSuffixes[ext] {
                if let img = materialIcon(name: iconName) { return img }
            }
        }

        // 3. Default file icon
        return materialImage(svgFilename: "file.svg")
    }

    // MARK: - Directory Icon Resolution

    private func directoryIcon(name: String, expanded: Bool, mapping: MaterialIconMapping) -> NSImage? {
        let normalized = normalizeDirectoryName(name)

        // Named directory icon
        if let pair = mapping.namedDirectories[normalized] {
            let svgFilename = expanded ? pair[1] : pair[0]
            if let img = materialImage(svgFilename: svgFilename) { return img }
        }

        // Default folder icon
        let svgFilename = expanded ? mapping.directoryIcons.expanded : mapping.directoryIcons.collapsed
        return materialImage(svgFilename: svgFilename)
    }

    /// Normalize directory name: lowercase, strip leading ./_ and trailing _.
    private func normalizeDirectoryName(_ name: String) -> String {
        var s = name.lowercased()
        while let first = s.first, first == "." || first == "_" { s = String(s.dropFirst()) }
        while s.last == "_" { s = String(s.dropLast()) }
        return s
    }
}
