import AppKit

// MARK: - Material Icon Mapping (JSON-driven)

/// Parsed from icon-mapping.json generated by scripts/generate-icon-mapping.py.
private struct MaterialIconMapping: Decodable {
    let fileIcons: [String: String]               // icon name -> SVG filename
    let fileSuffixes: [String: String]             // extension -> icon name
    let fileStems: [String: String]                // lowercase filename -> icon name
    let directoryIcons: DirectoryIcons             // default folder icons
    let namedDirectories: [String: [String]]       // dir name -> [collapsed.svg, expanded.svg]

    struct DirectoryIcons: Decodable {
        let collapsed: String
        let expanded: String
    }

    enum CodingKeys: String, CodingKey {
        case fileIcons = "file_icons"
        case fileSuffixes = "file_suffixes"
        case fileStems = "file_stems"
        case directoryIcons = "directory_icons"
        case namedDirectories = "named_directories"
    }
}

// MARK: - Icon Cache

/// Loads material file/folder icons (pre-colored SVGs), lazily on first access.
final class IconCache {

    // Material icons: pre-colored SVGs loaded lazily.
    private var materialImages: [String: NSImage] = [:]
    private var materialDir: URL?

    // Mapping data parsed from JSON.
    private var mapping: MaterialIconMapping?

    init() {
        loadMapping()
    }

    // MARK: - Setup

    private func loadMapping() {
        guard let iconsURL = Bundle.appResources.url(forResource: "icons", withExtension: nil) else {
            NSLog("IconCache: icons resource directory not found in bundle")
            return
        }
        let matDir = iconsURL.appendingPathComponent("material")
        materialDir = matDir

        let jsonURL = matDir.appendingPathComponent("icon-mapping.json")
        guard let data = try? Data(contentsOf: jsonURL) else {
            NSLog("IconCache: icon-mapping.json not found at \(jsonURL.path)")
            return
        }
        do {
            mapping = try JSONDecoder().decode(MaterialIconMapping.self, from: data)
        } catch {
            NSLog("IconCache: Failed to parse icon-mapping.json: \(error)")
        }
    }

    // MARK: - Material Icon Loading (lazy)

    /// Loads a material SVG by filename, caching the result.
    private func materialImage(svgFilename: String) -> NSImage? {
        if let cached = materialImages[svgFilename] {
            return cached
        }
        guard let dir = materialDir else { return nil }
        let url = dir.appendingPathComponent(svgFilename)
        guard let data = try? Data(contentsOf: url),
              let image = NSImage(data: data) else { return nil }
        image.size = NSSize(width: 16, height: 16)
        materialImages[svgFilename] = image
        return image
    }

    /// Resolves an icon name to an NSImage via the file_icons mapping.
    /// A material icon by name ("console", "image", …).
    func materialIcon(name: String) -> NSImage? {
        guard let svgFilename = mapping?.fileIcons[name] else { return nil }
        return materialImage(svgFilename: svgFilename)
    }

    // MARK: - Public API

    /// Returns the icon for a file or directory.
    func icon(filename: String, isDirectory: Bool, expanded: Bool) -> NSImage? {
        guard let mapping else { return nil }

        if isDirectory {
            return directoryIcon(name: filename, expanded: expanded, mapping: mapping)
        }
        return fileIcon(filename: filename, mapping: mapping)
    }

    // MARK: - File Icon Resolution

    private func fileIcon(filename: String, mapping: MaterialIconMapping) -> NSImage? {
        let lower = filename.lowercased()

        // 1. Exact filename match (e.g. "Dockerfile", ".gitignore")
        if let iconName = mapping.fileStems[lower] {
            if let img = materialIcon(name: iconName) { return img }
        }

        // 2. Extension match
        if let dotIndex = lower.lastIndex(of: ".") {
            let ext = String(lower[lower.index(after: dotIndex)...])
            if let iconName = mapping.fileSuffixes[ext] {
                if let img = materialIcon(name: iconName) { return img }
            }
        }

        // 3. Default file icon
        return materialImage(svgFilename: "file.svg")
    }

    // MARK: - Directory Icon Resolution

    private func directoryIcon(name: String, expanded: Bool, mapping: MaterialIconMapping) -> NSImage? {
        let normalized = normalizeDirectoryName(name)

        // Named directory icon
        if let pair = mapping.namedDirectories[normalized] {
            let svgFilename = expanded ? pair[1] : pair[0]
            if let img = materialImage(svgFilename: svgFilename) { return img }
        }

        // Default folder icon
        let svgFilename = expanded ? mapping.directoryIcons.expanded : mapping.directoryIcons.collapsed
        return materialImage(svgFilename: svgFilename)
    }

    /// Normalize directory name: lowercase, strip leading ./_ and trailing _.
    private func normalizeDirectoryName(_ name: String) -> String {
        var s = name.lowercased()
        while let first = s.first, first == "." || first == "_" { s = String(s.dropFirst()) }
        while s.last == "_" { s = String(s.dropLast()) }
        return s
    }
}
