#!/usr/bin/env bash
# Vendor the Lucide icon subset used by Impulse's chrome.
#
# Downloads each SVG from the pinned lucide-static release into vendor/lucide/
# and generates impulse-macos/Sources/ImpulseApp/DesignSystem/LucideIcons.swift
# (SVG sources compiled into the app, so no resource-copy step is needed).
# Lucide is ISC-licensed; the license is vendored alongside the icons.
#
# Usage: ./scripts/vendor-lucide.sh            (add names to ICONS below first)
set -euo pipefail

VERSION="1.52.0"
BASE="https://unpkg.com/lucide-static@${VERSION}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT}/vendor/lucide"
SWIFT_OUT="${ROOT}/impulse-macos/Sources/ImpulseApp/DesignSystem/LucideIcons.swift"

ICONS=(
  archive arrow-down arrow-up arrow-up-down bell bell-dot bookmark bot check
  chevron-down chevron-left chevron-right chevron-up chevrons-down-up chevrons-up-down
  circle circle-alert circle-check circle-dot circle-stop circle-x clipboard clock code
  columns-2 command copy corner-down-left ellipsis external-link eye eye-off file
  file-code file-diff file-plus files filter folder folder-git-2 folder-open folder-plus
  folder-tree git-branch git-branch-plus git-commit-horizontal git-compare git-fork
  git-graph git-merge git-pull-request globe history inbox info keyboard layers list
  list-filter list-tree loader-circle maximize-2 message-square minimize-2 minus
  package panel-bottom panel-left panel-right pencil pin pin-off play plug plus
  refresh-cw rotate-ccw rows-2 search settings sliders-horizontal square-terminal tag
  terminal trash-2 triangle-alert undo-2 upload user x zap
)

mkdir -p "${OUT_DIR}/icons" "$(dirname "${SWIFT_OUT}")"
curl -fsSL "${BASE}/LICENSE" -o "${OUT_DIR}/LICENSE"
echo "${VERSION}" > "${OUT_DIR}/VERSION"

for name in "${ICONS[@]}"; do
  curl -fsSL "${BASE}/icons/${name}.svg" -o "${OUT_DIR}/icons/${name}.svg" \
    || { echo "missing icon: ${name}" >&2; exit 1; }
done

python3 - "${OUT_DIR}/icons" "${SWIFT_OUT}" "${VERSION}" "${ICONS[@]}" <<'PY'
import re, sys
icon_dir, out, version, names = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4:]

def case_name(n):
    parts = n.split('-')
    s = parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])
    if s[0].isdigit():
        s = '_' + s
    return {'repeat': 'repeat_', 'import': 'import_', 'default': 'default_'}.get(s, s)

lines = [
    "// Generated by scripts/vendor-lucide.sh from lucide-static v%s (ISC License," % version,
    "// see vendor/lucide/LICENSE). Do not edit by hand; add icons to the script.",
    "",
    "/// Lucide icons used by Impulse's chrome. Render with `Icon(.name)`.",
    "enum LucideIcon: String, CaseIterable {",
]
for n in names:
    lines.append('  case %s = "%s"' % (case_name(n), n))
lines += ["", "  /// The icon's SVG source (24x24, stroke=currentColor).", "  var svg: String {", "    switch self {"]
for n in names:
    svg = open(f"{icon_dir}/{n}.svg").read()
    svg = re.sub(r'<!--.*?-->', '', svg, flags=re.S)
    svg = re.sub(r'\s+', ' ', svg).replace('> <', '><').strip()
    svg = re.sub(r'class="[^"]*"\s*', '', svg)
    lines.append('    case .%s:' % case_name(n))
    lines.append('      return #"%s"#' % svg)
lines += ["    }", "  }", "}", ""]
open(out, 'w').write('\n'.join(lines))
PY

echo "Vendored ${#ICONS[@]} Lucide icons (v${VERSION}) -> ${SWIFT_OUT}"
